IF OBJECT_ID('RUN_SHOW_GENERATE_BY_CREATE_ON') IS NOT NULL
	DROP PROC RUN_SHOW_GENERATE_BY_CREATE_ON
go
CREATE PROC RUN_SHOW_GENERATE_BY_CREATE_ON
AS
SELECT 
	lg.LICENSE_GENERATE_ID,
	lg.CREATE_ON,
	lg.CREATE_BY,
	lg.NOTE,
	lg.FOLLOW_UP_BY,
	lg.IS_ACTIVE
FROM TBL_LICENSE_GENERATE lg
INNER JOIN TBL_SCHEDULE s ON lg.SCHEDULE_ID = s.SCHEDULE_ID
INNER JOIN TBL_LICENSE l ON s.LICENSE_ID =l.LICENSE_ID