//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPowerGenerateLicense.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPowerGenerateLicense.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to គ្រប់រដូវកាល.
        /// </summary>
        internal static string ALL_SEASON {
            get {
                return ResourceManager.GetString("ALL_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះអ្នកប្រើមានរួចហើយ.
        /// </summary>
        internal static string ALREADY_USERNAME {
            get {
                return ResourceManager.GetString("ALREADY_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_icon_left {
            get {
                object obj = ResourceManager.GetObject("arrow-icon-left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backup {
            get {
                object obj = ResourceManager.GetObject("backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_search {
            get {
                object obj = ResourceManager.GetObject("icon-search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ព័ត៏មាន.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\SQLEXPRESS.
        /// </summary>
        internal static string INSTANCE_NAME {
            get {
                return ResourceManager.GetString("INSTANCE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខអាជ្ញាប័ណ្ឌមានហើយ.
        /// </summary>
        internal static string LICENSENUMBER_ADREADY {
            get {
                return ResourceManager.GetString("LICENSENUMBER_ADREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to នាក់.
        /// </summary>
        internal static string NEAK {
            get {
                return ResourceManager.GetString("NEAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap people {
            get {
                object obj = ResourceManager.GetObject("people", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to របាយការណ៏អ្នកកាន់អាជ្ញាប័ណ្ឌ.
        /// </summary>
        internal static string REPORT_LICENSE_ACOUNT {
            get {
                return ResourceManager.GetString("REPORT_LICENSE_ACOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to របាយការណ៏អាជ្ញាប័ណ្ឌមិនទាន់ចេញ.
        /// </summary>
        internal static string REPORT_LICENSE_AVAILABLE {
            get {
                return ResourceManager.GetString("REPORT_LICENSE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to របាយការណ៏ការចេញលេខអាជ្ញាប័ណ្ឌ.
        /// </summary>
        internal static string REPORT_LICENSE_GENERATE {
            get {
                return ResourceManager.GetString("REPORT_LICENSE_GENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញឈ្មោះគណនី.
        /// </summary>
        internal static string REQUIRED_ACCOUNTNAME {
            get {
                return ResourceManager.GetString("REQUIRED_ACCOUNTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញអស័យដ្ខាន.
        /// </summary>
        internal static string REQUIRED_ADDRESS {
            get {
                return ResourceManager.GetString("REQUIRED_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញអ្នកទំនាកទំនង.
        /// </summary>
        internal static string REQUIRED_CONTACTNAME {
            get {
                return ResourceManager.GetString("REQUIRED_CONTACTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញគោត្តនាម.
        /// </summary>
        internal static string REQUIRED_LASTNAME {
            get {
                return ResourceManager.GetString("REQUIRED_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញលេខអាជ្ញាប័ណ្ឌ.
        /// </summary>
        internal static string REQUIRED_LICENSENUMBER {
            get {
                return ResourceManager.GetString("REQUIRED_LICENSENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញលេខសំងាត់.
        /// </summary>
        internal static string REQUIRED_PASSWORD {
            get {
                return ResourceManager.GetString("REQUIRED_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញលេខទូរស័ព្ទ.
        /// </summary>
        internal static string REQUIRED_PHONE {
            get {
                return ResourceManager.GetString("REQUIRED_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញឈ្មោះខេត្ត.
        /// </summary>
        internal static string REQUIRED_PROVINCE_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_PROVINCE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញឈ្មោះរដូវកាល.
        /// </summary>
        internal static string REQUIRED_SEASON {
            get {
                return ResourceManager.GetString("REQUIRED_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សូមបំពេញឈ្មោះអ្នកប្រើ.
        /// </summary>
        internal static string REQUIRED_USERNAME {
            get {
                return ResourceManager.GetString("REQUIRED_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ឈ្មោះរដូវកាលមានរួចហើយ.
        /// </summary>
        internal static string SEASON_AREADY {
            get {
                return ResourceManager.GetString("SEASON_AREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ដំណើរកាបានជោគជ័យ.
        /// </summary>
        internal static string SUCCESSFULL {
            get {
                return ResourceManager.GetString("SUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap write {
            get {
                object obj = ResourceManager.GetObject("write", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to លេខសំងាត់មិនត្រូវទេ.
        /// </summary>
        internal static string WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("WRONG_PASSWORD", resourceCulture);
            }
        }
    }
}
