<?xml version="1.0" encoding="utf-8"?><Database Name="EPOWERLICENSE" Class="LicenseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=EPOWERLICENSE;Integrated Security=True" SettingsObjectName="EPowerGenerateLicense.Properties.Settings" SettingsPropertyName="EPOWERLICENSEConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TBL_COLOR_LICENSE" Member="TBL_COLOR_LICENSEs">
    <Type Name="TBL_COLOR_LICENSE">
      <Column Name="COLOR_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="COLOR_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_COMPANY" Member="TBL_COMPANies">
    <Type Name="TBL_COMPANY">
      <Column Name="COMPANY_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COMPANY_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_LICENSE_TYPE" Member="TBL_LICENSE_TYPEs">
    <Type Name="TBL_LICENSE_TYPE">
      <Column Name="LICENSE_TYPE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LICENSE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PERCENTAGE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COLOR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IS_ACTIVE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SCHEDULE" Member="TBL_SCHEDULEs">
    <Type Name="TBL_SCHEDULE">
      <Column Name="SCHEDULE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LICENSE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SEASON_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SEASON" Member="TBL_SEASONs">
    <Type Name="TBL_SEASON">
      <Column Name="SEASON_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SEASON_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IS_ACTIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USER" Member="TBL_USERs">
    <Type Name="TBL_USER">
      <Column Name="USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IS_ACTIVE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_UTILITY" Member="TBL_UTILITies">
    <Type Name="TBL_UTILITY">
      <Column Name="UTILITY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UTILITY_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UTILITY_DESCRIPTION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UTILITY_VALUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_LICENSE" Member="TBL_LICENSEs">
    <Type Name="TBL_LICENSE">
      <Column Name="LICENSE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LICENSE_NUMBER" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FIRST_NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LAST_NAME" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CONTACT_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_ON" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IS_ACTIVE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_LICENSE_GENERATE" Member="TBL_LICENSE_GENERATEs">
    <Type Name="TBL_LICENSE_GENERATE">
      <Column Name="LICENSE_GENERATE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SCHEDULE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_ON" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LAST_MODIFIED" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IS_ACTIVE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.RUN_SHOW_SEASON_AVAILABLE" Method="RUN_SHOW_SEASON_AVAILABLE">
    <ElementType Name="RUN_SHOW_SEASON_AVAILABLEResult">
      <Column Name="SEASON_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SEASON_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RUN_SHOW_ALL_SEASON" Method="RUN_SHOW_ALL_SEASON">
    <ElementType Name="RUN_SHOW_ALL_SEASONResult">
      <Column Name="SEASON_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SEASON_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TOTAL_LICENSE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="REMAIN_LICENSE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RUN_SHOW_NUMBER_AVAILABLE" Method="RUN_SHOW_NUMBER_AVAILABLE">
    <Parameter Name="SEASOND_ID" Parameter="sEASOND_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="RUN_SHOW_NUMBER_AVAILABLEResult">
      <Column Name="REMAIN_LICENSE" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RUN_SHOW_HISTORY_SURVEY" Method="RUN_SHOW_HISTORY_SURVEY">
    <Parameter Name="SEASON_ID" Parameter="sEASON_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="RUN_SHOW_HISTORY_SURVEYResult">
      <Column Name="ROW_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CREATE_ON" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL_LICENSE" Type="System.String" DbType="NVarChar(34)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RUN_SHOW_GENERATE_BY_CREATE_ON" Method="RUN_SHOW_GENERATE_BY_CREATE_ON">
    <Parameter Name="CREATE_ON" Parameter="cREATE_ON" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="RUN_SHOW_GENERATE_BY_CREATE_ONResult">
      <Column Name="LICENSE_GENERATE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCHEDULE_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_ON" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_BY" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FOLLOW_UP_BY" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LICENSE_NUMBER" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ACCOUNT_NAME" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="CONTACT_NAME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IS_ACTIVE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="COLOR_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>