IF OBJECT_ID('RUN_SHOW_HISTORY_SURVEY') IS NOT NULL
	DROP PROC RUN_SHOW_HISTORY_SURVEY
GO
CREATE PROC RUN_SHOW_HISTORY_SURVEY
AS
SELECT 
	lg.CREATE_ON, 
	lg.CREATE_BY, 
	COUNT(lg.SCHEDULE_ID) AS TOTAL_LICENSE
FROM TBL_LICENSE_GENERATE lg
INNER JOIN TBL_SCHEDULE s ON lg.SCHEDULE_ID= s.SCHEDULE_ID
INNER JOIN TBL_LICENSE l ON s.LICENSE_ID = l.LICENSE_ID
WHERE s.SEASON_ID=3
GROUP BY lg.CREATE_ON,lg.CREATE_BY
