IF OBJECT_ID('RUN_SHOW_NUMBER_AVAILABLE') IS NOT NULL
	DROP PROC RUN_SHOW_NUMBER_AVAILABLE
go
CREATE PROC RUN_SHOW_NUMBER_AVAILABLE
	@SEASOND_ID INT=1
AS
SELECT 
		
		REMAIN_LICENSE = COUNT(s.SCHEDULE_ID) - COUNT(lg.SCHEDULE_ID)
	FROM TBL_SEASON se
	LEFT JOIN TBL_SCHEDULE s ON se.SEASON_ID = s.SEASON_ID
	LEFT JOIN TBL_LICENSE_GENERATE lg ON s.SCHEDULE_ID = lg.SCHEDULE_ID
	WHERE se.IS_ACTIVE = 1 AND se.SEASON_ID=@SEASOND_ID
